//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Coder.rc
//
#define IDI_HIGHLIGHT_ICON              101
#define IDI_CODEFOLD_ICON               102
#define IDI_AUTOCOMPLETE_ICON           103
#define IDI_HIDELIST_ICON               104
#define IDI_SYNTAXTHEME_ICON            105
#define IDI_COLORTHEME_ICON             106
#define IDI_MARKCOLOR_01                107
#define IDI_MARKCOLOR_02                108
#define IDI_MARKCOLOR_03                109
#define IDI_MARKCOLOR_04                110
#define IDI_MARKCOLOR_05                111
#define IDI_MARKCOLOR_06                112
#define IDI_CODER                       113

#define IDD_GENERAL_SETUP               1001
#define IDD_GENERAL_VAREDIT             1002
#define IDD_GENERAL_LINK                1003
#define IDD_HIGHLIGHT_SETUP             1004
#define IDD_CODEFOLD_LIST               1005
#define IDD_CODEFOLD1_SETUP             1006
#define IDD_CODEFOLD2_SETUP             1007
#define IDD_AUTOCOMPLETE_SETUP          1008

#define IDC_GENERAL_CACHE_ENABLE        1101
#define IDC_GENERAL_DEFAULTALIAS_ENABLE 1102
#define IDC_GENERAL_DEFAULTALIAS_EDIT   1103
#define IDC_GENERAL_VARTHEME_NAME_LABEL 1104
#define IDC_GENERAL_VARTHEME_NAME       1105
#define IDC_GENERAL_VARTHEME_SAVE       1106
#define IDC_GENERAL_VARTHEME_DELETE     1107
#define IDC_GENERAL_VARTHEME_LINK       1108
#define IDC_GENERAL_VARTHEME_LIST       1109
#define IDC_GENERAL_ADDITEM             1110
#define IDC_GENERAL_MODITEM             1111
#define IDC_GENERAL_MOVEDOWNITEM        1112
#define IDC_GENERAL_MOVEUPITEM          1113
#define IDC_GENERAL_DELITEM             1114
#define IDC_GENERAL_VARNAME_LABEL       1115
#define IDC_GENERAL_VARNAME             1116
#define IDC_GENERAL_VARVALUE_LABEL      1117
#define IDC_GENERAL_VARVALUE            1118
#define IDC_GENERAL_LINKLIST            1119
#define IDC_GENERAL_LINKCLEARITEM       1120

#define IDC_HIGHLIGHT_SETUP_GLOBAL_FONTSTYLE_GROUP       2001
#define IDC_HIGHLIGHT_SETUP_GLOBAL_FONTSTYLE_NORMAL      2002
#define IDC_HIGHLIGHT_SETUP_GLOBAL_FONTSTYLE_BOLD        2003
#define IDC_HIGHLIGHT_SETUP_GLOBAL_FONTSTYLE_ITALIC      2004
#define IDC_HIGHLIGHT_SETUP_AUTOMARK_GROUP               2005
#define IDC_HIGHLIGHT_SETUP_AUTOMARK_ENABLE              2006
#define IDC_HIGHLIGHT_SETUP_AUTOMARK_SYMBOLS             2007
#define IDC_HIGHLIGHT_SETUP_AUTOMARK_WORDS               2008

#define IDC_CODEFOLD_TITLETEXT                            3001
#define IDC_CODEFOLD_HIDE                                 3002
#define IDC_CODEFOLD_CLOSE                                3003
#define IDC_CODEFOLD_LIST                                 3004
#define IDC_CODEFOLD_FILTER                               3005
#define IDC_CODEFOLD_SETUP_SHOWDOCK_GROUP                 3006
#define IDC_CODEFOLD_SETUP_SHOWDOCK_AUTO                  3007
#define IDC_CODEFOLD_SETUP_SHOWDOCK_ALWAYS                3008
#define IDC_CODEFOLD_SETUP_SHOWDOCK_NONE                  3009
#define IDC_CODEFOLD_SETUP_SHOWDOCK_FOLDLIMIT_LABEL       3010
#define IDC_CODEFOLD_SETUP_SHOWDOCK_FOLDLIMIT             3011
#define IDC_CODEFOLD_SETUP_FOLLOWCARET_GROUP              3012
#define IDC_CODEFOLD_SETUP_FOLLOWCARET_ANYWHERE           3013
#define IDC_CODEFOLD_SETUP_FOLLOWCARET_ONLYROOT           3014
#define IDC_CODEFOLD_SETUP_FOLLOWCARET_NONE               3015
#define IDC_CODEFOLD_SETUP_CHARSLIMIT_GROUP               3016
#define IDC_CODEFOLD_SETUP_CHARSLIMIT                     3017
#define IDC_CODEFOLD_SETUP_CHARSLIMIT_POSTLABEL           3018
#define IDC_CODEFOLD_SETUP_DRAWNODE_GROUP                 3019
#define IDC_CODEFOLD_SETUP_DRAWNODE_SQUARE                3020
#define IDC_CODEFOLD_SETUP_DRAWNODE_ROUND                 3021
#define IDC_CODEFOLD_SETUP_TAGMARK                        3022
#define IDC_CODEFOLD_SETUP_COLLAPSEONOPEN                 3023
#define IDC_CODEFOLD_SETUP_NOPRINTCOLLAPSED               3024
#define IDC_CODEFOLD_SETUP_FINDROOT_GROUP                 3025
#define IDC_CODEFOLD_SETUP_FINDROOTHOTKEY_LABEL           3026
#define IDC_CODEFOLD_SETUP_FINDROOTHOTKEY                 3027
#define IDC_CODEFOLD_SETUP_FINDROOTDEPTH_LABEL            3028
#define IDC_CODEFOLD_SETUP_FINDROOTDEPTH_EDIT             3029
#define IDC_CODEFOLD_SETUP_FINDROOTDEPTH_SPIN             3030
#define IDC_CODEFOLD_SETUP_HOTKEYCURRENT_GROUP            3031
#define IDC_CODEFOLD_SETUP_HOTKEYCURRENT_COLLAPSE_LABEL   3032
#define IDC_CODEFOLD_SETUP_HOTKEYCURRENT_COLLAPSE         3033
#define IDC_CODEFOLD_SETUP_HOTKEYCURRENT_GOBEGIN_LABEL    3034
#define IDC_CODEFOLD_SETUP_HOTKEYCURRENT_GOBEGIN          3035
#define IDC_CODEFOLD_SETUP_HOTKEYCURRENT_GOEND_LABEL      3036
#define IDC_CODEFOLD_SETUP_HOTKEYCURRENT_GOEND            3037
#define IDC_CODEFOLD_SETUP_HOTKEYCURRENT_SELECT_LABEL     3038
#define IDC_CODEFOLD_SETUP_HOTKEYCURRENT_SELECT           3039
#define IDC_CODEFOLD_SETUP_HOTKEYALL_GROUP                3040
#define IDC_CODEFOLD_SETUP_HOTKEYALL_COLLAPSE_LABEL       3041
#define IDC_CODEFOLD_SETUP_HOTKEYALL_COLLAPSE             3042
#define IDC_CODEFOLD_SETUP_HOTKEYALL_NEXTLEVEL_LABEL      3043
#define IDC_CODEFOLD_SETUP_HOTKEYALL_NEXTLEVEL            3044
#define IDC_CODEFOLD_SETUP_HOTKEYALL_PREVLEVEL_LABEL      3045
#define IDC_CODEFOLD_SETUP_HOTKEYALL_PREVLEVEL            3046

#define IDC_AUTOCOMPLETE_SETUP_AUTOLIST_GROUP                4001
#define IDC_AUTOCOMPLETE_SETUP_AUTOLIST_ENABLE               4002
#define IDC_AUTOCOMPLETE_SETUP_AUTOLISTAFTER_LABEL           4003
#define IDC_AUTOCOMPLETE_SETUP_AUTOLISTAFTER_PRELABEL        4004
#define IDC_AUTOCOMPLETE_SETUP_AUTOLISTAFTER_POSTLABEL       4005
#define IDC_AUTOCOMPLETE_SETUP_AUTOLISTAFTER                 4006
#define IDC_AUTOCOMPLETE_SETUP_AUTOLISTAFTER_SPIN            4007
#define IDC_AUTOCOMPLETE_SETUP_HOTKEY_GROUP                  4008
#define IDC_AUTOCOMPLETE_SETUP_HOTKEY_COMPLETEWITHLIST_LABEL 4009
#define IDC_AUTOCOMPLETE_SETUP_HOTKEY_COMPLETEWITHLIST       4010
#define IDC_AUTOCOMPLETE_SETUP_HOTKEY_COMPLETENEXT_LABEL     4011
#define IDC_AUTOCOMPLETE_SETUP_HOTKEY_COMPLETENEXT           4012
#define IDC_AUTOCOMPLETE_SETUP_HOTKEY_COMPLETEPREV_LABEL     4013
#define IDC_AUTOCOMPLETE_SETUP_HOTKEY_COMPLETEPREV           4014
#define IDC_AUTOCOMPLETE_SETUP_DOCUMENTWORDS_GROUP           4015
#define IDC_AUTOCOMPLETE_SETUP_ADDDOCUMENTWORDS              4016
#define IDC_AUTOCOMPLETE_SETUP_MAXDOCUMENT_ENABLE            4017
#define IDC_AUTOCOMPLETE_SETUP_MAXDOCUMENT_CHARS             4018
#define IDC_AUTOCOMPLETE_SETUP_MAXDOCUMENT_POSTLABEL         4019
#define IDC_AUTOCOMPLETE_SETUP_COMPLETENONSYNTAXDOCUMENT     4020
#define IDC_AUTOCOMPLETE_SETUP_ADDHIGHLIGHTWORDS             4021
#define IDC_AUTOCOMPLETE_SETUP_RIGHTDELIMITERS_ENABLE        4022
#define IDC_AUTOCOMPLETE_SETUP_SYNTAXDELIMITERS_ENABLE       4023

#define IDM_CODEFOLD_SETUP                       5001
#define IDM_CODEFOLD_GOBEGIN                     5002
#define IDM_CODEFOLD_GOEND                       5003
#define IDM_CODEFOLD_SELECT                      5004
#define IDM_CODEFOLD_INVIEW                      5005
#define IDM_CODEFOLD_LISTEXPAND                  5006
#define IDM_CODEFOLD_LISTCOLLAPSE                5007
#define IDM_CODEFOLD_STATISTICS                  5008
#define IDC_STATIC                      -1

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        11001
#define _APS_NEXT_COMMAND_VALUE         12001
#define _APS_NEXT_CONTROL_VALUE         13001
#define _APS_NEXT_SYMED_VALUE           14001
#endif
#endif
